// <auto-generated />
using System;
using Library_DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_DataAccess.Context.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library_Core.Entities.Concrete.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7144),
                            Description = "Joanne Rowling CH, OBE, HonFRSE, FRCPE, FRSL, better known by her pen name J. K. Rowling, is a British author, philanthropist, film producer, television producer, and screenwriter. She is best known for writing the Harry Potter fantasy series, which has won multiple awards and sold more than 500 million copies, becoming the best-selling book series in history. The books are the basis of a popular film series, over which Rowling had overall approval on the scripts and was a producer on the final films. She also writes crime novels under the pen name Robert Galbraith.",
                            Name = "J.K. Rowling",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7157),
                            Description = "Stephen Edwin King is an American author of horror, supernatural fiction, suspense, crime, science-fiction, and fantasy novels. His books have sold more than 350 million copies, and many have been adapted into films, television series, miniseries, and comic books. King has published 61 novels, including seven under the pen name Richard Bachman, and five non-fiction books. He has also written approximately 200 short stories, most of which have been published in book collections.",
                            Name = "Stephen King",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7159),
                            Description = "John Ronald Reuel Tolkien was an English writer, poet, philologist, and academic, best known as the author of the high fantasy works The Hobbit, The Lord of the Rings, and The Silmarillion.",
                            Name = "J.R.R. Tolkien",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7160),
                            Description = "George Raymond Richard Martin, also known as GRRM, is an American novelist and short story writer in the fantasy, horror, and science fiction genres, screenwriter, and television producer. He is best known for his series of epic fantasy novels, A Song of Ice and Fire, which was adapted into the HBO series Game of Thrones.",
                            Name = "George R.R. Martin",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7161),
                            Description = "Dame Agatha Mary Clarissa Christie, Lady Mallowan, was an English writer known for her sixty-six detective novels and fourteen short story collections, particularly those revolving around fictional detectives Hercule Poirot and Miss Marple. She also wrote the world's longest-running",
                            Name = "Agatha Christie",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7163),
                            Description = "Daniel Gerhard Brown is an American author best known for his thriller novels, including the Robert Langdon novels Angels & Demons, The Da Vinci Code, The Lost Symbol, Inferno, and Origin. His novels are treasure hunts that usually take place over a period of 24 hours. They feature recurring themes of cryptography, art, and conspiracy theories. His books have been translated into 57 languages and, as of 2012, have sold over 200 million copies. Three of them, Angels & Demons, The Da Vinci Code, and Inferno, have been adapted into films.",
                            Name = "Dan Brown",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7164),
                            Description = "Sir Arthur Ignatius Conan Doyle KStJ DL was a British writer and physician. He created the character Sherlock Holmes in 1887 for A Study in Scarlet, the first of four novels and fifty-six short stories about Holmes and Dr. Watson. The Sherlock Holmes stories are considered milestones in the field of crime fiction.",
                            Name = "Arthur Conan Doyle",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7165),
                            Description = "Samuel Langhorne Clemens, known by his pen name Mark Twain, was an American writer, humorist, entrepreneur, publisher, and lecturer. He was lauded as the 'greatest humorist the United States has produced,' and William Faulkner called him 'the father of American literature'. His novels include The Adventures of Tom Sawyer and its sequel, the Adventures of Huckleberry Finn, the latter often called 'The Great American Novel'.",
                            Name = "Mark Twain",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7166),
                            Description = "Count Lev Nikolayevich Tolstoy, usually referred to in English as Leo Tolstoy, was a Russian writer who is regarded as one of the greatest authors of all time. He received multiple nominations for the Nobel Prize in Literature every year from 1902 to 1906 and nominations for the Nobel Peace Prize in 1901, 1902, and 1910, and his miss of the prize is a major Nobel prize controversy.",
                            Name = "Leo Tolstoy",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7168),
                            Description = "Fyodor Mikhailovich Dostoevsky, sometimes transliterated Dostoyevsky, was a Russian novelist, philosopher, short story writer, essayist, and journalist. Dostoevsky's literary works explore human psychology in the troubled political, social, and spiritual atmospheres of 19th-century Russia, and engage with a variety of philosophical and religious themes. His most acclaimed works include Crime and Punishment, The Idiot, Demons, and The Brothers Karamazov. Dostoevsky's body of works consists of 12 novels, four novellas, 16 short stories, and numerous other works.",
                            Name = "Fyodor Dostoevsky",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7169),
                            Description = "Ernest Miller Hemingway was an American novelist, short-story writer, journalist, and sportsman. His economical and understated style—which he termed the iceberg theory—had a strong influence on 20th-century fiction, while his adventurous lifestyle and his public image brought him admiration from later generations. Hemingway produced most of his work between the mid-1920s and the mid-1950s, and he was awarded the Nobel Prize in Literature in 1954.",
                            Name = "Ernest Hemingway",
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7170),
                            Description = "Sabahattin Ali was a Turkish novelist, short-story writer, poet, and journalist. He was born in 1907 in Eğridere township of the Sanjak of Gümülcine (now Komotini in Greece), in the Ottoman Empire, to an Albanian family. He was killed by Ali Ertekin, a government official, on 2 July 1948.",
                            Name = "Sabahattin Ali",
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7171),
                            Description = "Ferit Orhan Pamuk is a Turkish novelist, screenwriter, academic, and recipient of the 2006 Nobel Prize in Literature. One of Turkey's most prominent novelists, his work has sold over thirteen million books in sixty-three languages, making him the country's best-selling writer.",
                            Name = "Orhan Pamuk",
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7172),
                            Description = "Franz Kafka was a German-speaking Bohemian writer of novels and short stories, regarded by critics as one of the most significant writers of the 20th century. His work, which fuses elements of realism and the fantastic, typically features isolated protagonists facing bizarre or surrealistic predicaments and incomprehensible socio-bureaucratic powers, and has been interpreted as exploring themes of alienation, existential anxiety, guilt, and absurdity. His best known works include 'Die Verwandlung' ('The Metamorphosis'), Der Process (The Trial), and Das Schloss (The Castle).",
                            Name = "Franz Kafka",
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7173),
                            Description = "Albert Camus was a French philosopher, author, and journalist. He won the Nobel Prize in Literature at the age of 44 in 1957, the second-youngest recipient in history. His works include The Stranger, The Plague, The Myth of Sisyphus, The Fall, and The Rebel.",
                            Name = "Albert Camus",
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7174),
                            Description = "Hermann Karl Hesse was a German-born Swiss poet, novelist, and painter. His best-known works include Demian, Steppenwolf, Siddhartha, and The Glass Bead Game, each of which explores an individual's search for authenticity, self-knowledge and spirituality. In 1946, he received the Nobel Prize in Literature.",
                            Name = "Hermann Hesse",
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7175),
                            Description = "Halide Edib Adıvar was a Turkish novelist, nationalist, and political leader. ",
                            Name = "Halide Edib Adıvar",
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7176),
                            Description = "Nazım Hikmet Ran, commonly known as Nazım Hikmet, was a Turkish poet, playwright, novelist, screenwriter, director, and memoirist. He was acclaimed for the 'lyrical flow of his statements'.",
                            Name = "Nazım Hikmet",
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7177),
                            Description = "Ahmet Hamdi Tanpınar was a Turkish poet, novelist, literary historian, and essayist widely regarded as one of the most important representatives of modernism in Turkish literature. He was also a member of the Turkish Parliament.",
                            Name = "Ahmet Hamdi Tanpınar",
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7179),
                            Description = "Yusuf Atılgan was a Turkish novelist and playwright. He is best known for his novels Aylak Adam and Anayurt Oteli.",
                            Name = "Yusuf Atılgan",
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7180),
                            Description = "Yaşar Kemal was a Turkish writer and human rights activist. He received 38 awards during his lifetime and had been a candidate for the Nobel Prize in Literature on the strength of Memed, My Hawk.",
                            Name = "Yaşar Kemal",
                            Status = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7181),
                            Description = "Orhan Veli Kanık was a Turkish poet. He is considered one of the pioneers of modern poetry in Turkey.",
                            Name = "Orhan Veli Kanık",
                            Status = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7182),
                            Description = "Cemal Süreya was a Turkish poet and writer. He was one of the greatest Turkish poets of the 20th century.",
                            Name = "Cemal Süreya",
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7183),
                            Description = "Attilâ İlhan was a Turkish poet, novelist, essayist, journalist, and reviewer. He was a prominent member of the Turkish literary scene in the 20th century.",
                            Name = "Attilâ İlhan",
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7184),
                            Description = "Oğuz Atay was a Turkish novelist, playwright, and engineer. He is best known for his novels Tutunamayanlar and Tehlikeli Oyunlar.",
                            Name = "Oğuz Atay",
                            Status = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7185),
                            Description = "Necip Fazıl Kısakürek was a Turkish poet, novelist, playwright, and philosopher. He was also a political activist, supporting the ideology of Turkish nationalism and Islamism, and was a prominent member of the Turkish Hearth Party.",
                            Name = "Necip Fazıl Kısakürek",
                            Status = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7186),
                            Description = "Peyami Safa was a Turkish novelist, storywriter, playwright, essayist, and poet. He is considered one of the greatest Turkish novelists of the 20th century.",
                            Name = "Peyami Safa",
                            Status = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7187),
                            Description = "Reşat Nuri Güntekin was a Turkish novelist, storywriter, playwright, and poet. He was also a prominent and pioneering academic, journalist, and essayist. He is best known for his novels Çalıkuşu and Yaprak Dökümü.",
                            Name = "Reşat Nuri Güntekin",
                            Status = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7188),
                            Description = "Yakup Kadri Karaosmanoğlu was a Turkish novelist, playwright, and journalist. He was one of the leading Turkish novelists of the Republican era.",
                            Name = "Yakup Kadri",
                            Status = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7189),
                            Description = "Ömer Seyfettin was a Turkish writer, known primarily for his short stories and articles. His stories are written in a clear and precise style and are realistic in nature. They avoid sentimentality and melodrama, and are often concerned with the relationship between people and their environment.",
                            Name = "Ömer Seyfettin",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Library_Core.Entities.Concrete.AuthorPublisher", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.HasKey("AuthorId", "PublisherId");

                    b.HasIndex("PublisherId");

                    b.ToTable("AuthorPublishers");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            PublisherId = 1
                        },
                        new
                        {
                            AuthorId = 2,
                            PublisherId = 2
                        },
                        new
                        {
                            AuthorId = 3,
                            PublisherId = 3
                        },
                        new
                        {
                            AuthorId = 4,
                            PublisherId = 4
                        },
                        new
                        {
                            AuthorId = 5,
                            PublisherId = 5
                        },
                        new
                        {
                            AuthorId = 6,
                            PublisherId = 6
                        },
                        new
                        {
                            AuthorId = 7,
                            PublisherId = 7
                        },
                        new
                        {
                            AuthorId = 8,
                            PublisherId = 8
                        },
                        new
                        {
                            AuthorId = 9,
                            PublisherId = 9
                        },
                        new
                        {
                            AuthorId = 10,
                            PublisherId = 10
                        },
                        new
                        {
                            AuthorId = 11,
                            PublisherId = 11
                        },
                        new
                        {
                            AuthorId = 12,
                            PublisherId = 12
                        });
                });

            modelBuilder.Entity("Library_Core.Entities.Concrete.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BorrowedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFavorited")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            BorrowedCount = 0,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7306),
                            Description = "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle.",
                            GenreId = 1,
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg",
                            IsFavorited = false,
                            Language = "English",
                            Name = "Harry Potter and the Philosopher’s Stone",
                            PageCount = 223,
                            PublishYear = 1997,
                            PublisherId = 1,
                            Rating = 5,
                            Status = 1,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            BorrowedCount = 0,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7312),
                            Description = "The Dursleys were so mean and hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike.",
                            GenreId = 1,
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg",
                            IsFavorited = false,
                            Language = "English",
                            Name = "Harry Potter and the Chamber of Secrets",
                            PageCount = 251,
                            PublishYear = 1998,
                            PublisherId = 1,
                            Rating = 5,
                            Status = 1,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            BorrowedCount = 0,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7316),
                            Description = "To the children, the town was their whole world. To the adults, knowing better, Derry, Maine was just their home town: familiar, well-ordered for the most part. A good place to live.",
                            GenreId = 2,
                            ImageUrl = "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-173540-IT.jpg?w=1280",
                            IsFavorited = false,
                            Language = "English",
                            Name = "It",
                            PageCount = 1138,
                            PublishYear = 1986,
                            PublisherId = 2,
                            Rating = 5,
                            Status = 1,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            BorrowedCount = 0,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7319),
                            Description = "Jack Torrance’s new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he’ll have plenty of time to spend reconnecting with his family and working on his writing.",
                            GenreId = 2,
                            ImageUrl = "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-173546-The-Shining.jpg?w=1280",
                            IsFavorited = false,
                            Language = "English",
                            Name = "The Shining",
                            PageCount = 447,
                            PublishYear = 1977,
                            PublisherId = 2,
                            Rating = 5,
                            Status = 1,
                            StockCount = 10
                        });
                });

            modelBuilder.Entity("Library_Core.Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7450),
                            Status = 1,
                            UserComment = "Great book!",
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7453),
                            Status = 1,
                            UserComment = "I loved it!",
                            Username = "janedoe"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7454),
                            Status = 1,
                            UserComment = "I couldn't put it down!",
                            Username = "jackdoe"
                        });
                });

            modelBuilder.Entity("Library_Core.Entities.Concrete.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7545),
                            Name = "Story",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7547),
                            Name = "Novel",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7548),
                            Name = "Poem",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7549),
                            Name = "Drama",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7550),
                            Name = "Comedy",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7551),
                            Name = "Tragedy",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7552),
                            Name = "Fiction",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7553),
                            Name = "Non-Fiction",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7554),
                            Name = "Fantasy",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7555),
                            Name = "Science Fiction",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7555),
                            Name = "Mystery",
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7557),
                            Name = "Horror",
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7558),
                            Name = "Romance",
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7559),
                            Name = "Biography",
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7559),
                            Name = "Autobiography",
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7560),
                            Name = "Memoir",
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7561),
                            Name = "Self-Help",
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7562),
                            Name = "History",
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7563),
                            Name = "Travel",
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7564),
                            Name = "Cooking",
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7565),
                            Name = "Art",
                            Status = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7566),
                            Name = "Photography",
                            Status = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7567),
                            Name = "Children",
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7568),
                            Name = "Young Adult",
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7569),
                            Name = "Adult",
                            Status = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7570),
                            Name = "Science",
                            Status = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7570),
                            Name = "Mathematics",
                            Status = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7571),
                            Name = "Physics",
                            Status = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7572),
                            Name = "Chemistry",
                            Status = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7573),
                            Name = "Biology",
                            Status = 1
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7574),
                            Name = "Astronomy",
                            Status = 1
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7575),
                            Name = "Geology",
                            Status = 1
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7576),
                            Name = "Meteorology",
                            Status = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7577),
                            Name = "Psychology",
                            Status = 1
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7578),
                            Name = "Sociology",
                            Status = 1
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7579),
                            Name = "Philosophy",
                            Status = 1
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7580),
                            Name = "Religion",
                            Status = 1
                        },
                        new
                        {
                            Id = 38,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7581),
                            Name = "Mythology",
                            Status = 1
                        },
                        new
                        {
                            Id = 39,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7581),
                            Name = "Folklore",
                            Status = 1
                        },
                        new
                        {
                            Id = 40,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7582),
                            Name = "Fairy Tale",
                            Status = 1
                        },
                        new
                        {
                            Id = 41,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7583),
                            Name = "Legend",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Library_Core.Entities.Concrete.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7714),
                            Name = "Penguin Random House",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7716),
                            Name = "HarperCollins",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7717),
                            Name = "Simon & Schuster",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7718),
                            Name = "Hachette Livre",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7719),
                            Name = "Macmillan Publishers",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7720),
                            Name = "Pearson Education",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7721),
                            Name = "Scholastic",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7722),
                            Name = "Cengage Learning",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7723),
                            Name = "Wiley",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7724),
                            Name = "McGraw-Hill Education",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7725),
                            Name = "Houghton Mifflin Harcourt",
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7726),
                            Name = "Harlequin Enterprises",
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7727),
                            Name = "Bloomsbury Publishing",
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7728),
                            Name = "Cambridge University Press",
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7729),
                            Name = "Oxford University Press",
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7730),
                            Name = "Elsevier",
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7731),
                            Name = "Taylor & Francis",
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7732),
                            Name = "Springer",
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7733),
                            Name = "John Wiley & Sons",
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7734),
                            Name = "SAGE Publications",
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7735),
                            Name = "Kapra Yayıncılık",
                            Status = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7736),
                            Name = "Doğan Kitap",
                            Status = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7768),
                            Name = "İthaki Yayınları",
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7769),
                            Name = "Koridor Yayıncılık",
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7770),
                            Name = "Can Yayınları",
                            Status = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7771),
                            Name = "Kırmızı Kedi Yayınevi",
                            Status = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7772),
                            Name = "Pegasus Yayınları",
                            Status = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7773),
                            Name = "İnkılap Kitabevi",
                            Status = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7774),
                            Name = "Everest Yayınları",
                            Status = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7775),
                            Name = "Yapı Kredi Yayınları",
                            Status = 1
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7776),
                            Name = "Metis Yayınları",
                            Status = 1
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7777),
                            Name = "İletişim Yayınları",
                            Status = 1
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7778),
                            Name = "Can Çocuk Yayınları",
                            Status = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7779),
                            Name = "Timaş Yayınları",
                            Status = 1
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7780),
                            Name = "Domingo Yayınevi",
                            Status = 1
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7781),
                            Name = "Kolektif Kitap",
                            Status = 1
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7782),
                            Name = "İş Bankası Kültür Yayınları",
                            Status = 1
                        },
                        new
                        {
                            Id = 38,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7783),
                            Name = "Remzi Kitabevi",
                            Status = 1
                        },
                        new
                        {
                            Id = 39,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7784),
                            Name = "Yordam Kitap",
                            Status = 1
                        },
                        new
                        {
                            Id = 40,
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7785),
                            Name = "Liberus",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Library_Core.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7902),
                            Email = "johndoe@test.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "123",
                            Status = 1,
                            UserName = "johndoe"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7908),
                            Email = "janedoe@test.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            Password = "123",
                            Status = 1,
                            UserName = "janedoe"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 5, 12, 17, 26, 41, 430, DateTimeKind.Local).AddTicks(7910),
                            Email = "jackdoe@test.com",
                            FirstName = "Jack",
                            LastName = "Doe",
                            Password = "123",
                            Status = 1,
                            UserName = "jackdoe"
                        });
                });

            modelBuilder.Entity("Library_Core.Entities.Concrete.AuthorPublisher", b =>
                {
                    b.HasOne("Library_Core.Entities.Concrete.Author", "Author")
                        .WithMany("Publishers")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library_Core.Entities.Concrete.Publisher", "Publisher")
                        .WithMany("Authors")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Library_Core.Entities.Concrete.Book", b =>
                {
                    b.HasOne("Library_Core.Entities.Concrete.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library_Core.Entities.Concrete.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library_Core.Entities.Concrete.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Library_Core.Entities.Concrete.Comment", b =>
                {
                    b.HasOne("Library_Core.Entities.Concrete.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library_Core.Entities.Concrete.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Library_Core.Entities.Concrete.Author", b =>
                {
                    b.Navigation("Publishers");
                });

            modelBuilder.Entity("Library_Core.Entities.Concrete.Publisher", b =>
                {
                    b.Navigation("Authors");
                });

            modelBuilder.Entity("Library_Core.Entities.Concrete.User", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
